/*  Fernández Martínez José Ismael
    Trinidad Hernández Norma Verónica
    Vilchis Domínguez Miguel Alonso
    Práctica 03
    Oct 2014
*/
class Node;
class LeafNode;
class Niterador;
class NodeList;
class LNodeList;
class VNodeList;
class INode;
class BlockNode;
class BinNode;
class UnaNode;
class IntNode;
class StringNode;
class IdentificadorNode;
//class BoolNode;
class TrueNode;
class FalseNode;
class ContinueNode;
class PassNode;
class BreakNode;
class FloatNode;
class IdentacionNode;
class IfNode;
class ElIfNode;
class ForNode;
class ReturnNode;
class PrintNode;
class GlobalNode;
class FuncionNode;
class ExecNode;
class WhileNode;
class IsNode;
class AndNode;
class OrNode;
class PorNode;
class MenosNode;
class MasNode;
class DivNode;
class IgualNode;
class DifNode;
class MenorNode;
class MayorNode;
class MenIgNode;
class MayIgNode;
class ModNode;
class DelNode;
class NotNode;
class WithNode;
class AsNode;
class NIgNode;
class DIgNode;
class EnetildeNode;
class CircunflejoNode;
class PipeNode;
class AmpersonNode;
class DMayorNode;
class DMenorNode;
class ModNode;
class DDiagNode;
class DAsteriscosNode;
class AParenNode;
class CParenNode;
class ACorcheteNode;
class CCorcheteNode;
class ALlaveNode;
class CLlaveNode;
class ComaNode;
class DPuntoNode;
class PuntoNode;
class PComaNode;
class MasIgualNode;
class MenosIgualNode;
class AsIgualNode;
class DiaIgualNode;
class DDiaIgualNode;
class PorIgualNode;
class AmpIgualNode;
class PipeIgualNode;
class CircIgualNode;
class DMayorIgualNode;
class DMenorIgualNode;
class DAstIgualNode;
class MenorMayorNode;
class NewLineNode;
class DentacionNode;
class PrintVisitor;
class NodeVisitor{
protected:
	NodeVisitor(){}
public:
	virtual void visit(IntNode*) = 0;
	virtual void visit(StringNode*) = 0;
	virtual void visit(IdentificadorNode*) = 0;
	//virtual void visit(BoolNode*) = 0;
	virtual void visit(TrueNode*) = 0;
	virtual void visit(FalseNode*) = 0;
	virtual void visit(ContinueNode*) = 0;
	virtual void visit(PassNode*) = 0;
	virtual void visit(BreakNode*) = 0;
	virtual void visit(FloatNode*) = 0;
	virtual void visit(IdentacionNode*) = 0;
	virtual void visit(IfNode*) = 0;
	virtual void visit(ElIfNode*) = 0;
	virtual void visit(ForNode*) = 0;
	virtual void visit(ReturnNode*) = 0;
	virtual void visit(PrintNode*) = 0;
	virtual void visit(GlobalNode*) = 0;
	virtual void visit(FuncionNode*) = 0;
	virtual void visit(ExecNode*) = 0;
	virtual void visit(WhileNode*) = 0;
	virtual void visit(IsNode*) = 0;
	virtual void visit(AndNode*) = 0;
	virtual void visit(OrNode*) = 0;
	virtual void visit(PorNode*) = 0;
	virtual void visit(MenosNode*) = 0;
	virtual void visit(MasNode*) = 0;
	virtual void visit(DivNode*) = 0;
	virtual void visit(IgualNode*) = 0;
	virtual void visit(DifNode*) = 0;
	virtual void visit(MenorNode*) = 0;
	virtual void visit(MayorNode*) = 0;
	virtual void visit(MenIgNode*) = 0;
	virtual void visit(MayIgNode*) = 0;
	virtual void visit(ModNode*) = 0;
	virtual void visit(DelNode*) = 0;
	virtual void visit(NotNode*) = 0;
	virtual void visit(WithNode*) = 0;
	virtual void visit(AsNode*) = 0;
	virtual void visit(NIgNode*) = 0;
	virtual void visit(DIgNode*) = 0;
	virtual void visit(EnetildeNode*) = 0;
	virtual void visit(CircunflejoNode*) = 0;
	virtual void visit(PipeNode*) = 0;
	virtual void visit(AmpersonNode*) = 0;
	virtual void visit(DMayorNode*) = 0;
	virtual void visit(DMenorNode*) = 0;
	virtual void visit(DDiagNode*) = 0;
	virtual void visit(DAsteriscosNode*) = 0;
	virtual void visit(AParenNode*) = 0;
	virtual void visit(CParenNode*) = 0;
	virtual void visit(ACorcheteNode*) = 0;
	virtual void visit(CCorcheteNode*) = 0;
	virtual void visit(ALlaveNode*) = 0;
	virtual void visit(CLlaveNode*) = 0;
	virtual void visit(ComaNode*) = 0;
	virtual void visit(DPuntoNode*) = 0;
	virtual void visit(PuntoNode*) = 0;
	virtual void visit(PComaNode*) = 0;
	virtual void visit(MasIgualNode*) = 0;
	virtual void visit(MenosIgualNode*) = 0;
	virtual void visit(AsIgualNode*) = 0;
	virtual void visit(DiaIgualNode*) = 0;
	virtual void visit(DDiaIgualNode*) = 0;
	virtual void visit(PorIgualNode*) = 0;
	virtual void visit(AmpIgualNode*) = 0;
	virtual void visit(PipeIgualNode*) = 0;
	virtual void visit(CircIgualNode*) = 0;
	virtual void visit(DMayorIgualNode*) = 0;
	virtual void visit(DMenorIgualNode*) = 0;
	virtual void visit(DAstIgualNode*) = 0;
	virtual void visit(MenorMayorNode*) = 0;
	virtual void visit(NewLineNode*) = 0;
	virtual void visit(DentacionNode*) = 0;
};
class ASTBuilder{
public:
	virtual Node * bINTNode () = 0;
	virtual Node * bOPERADORNode () = 0;
//	virtual Node * bBOOLNode () = 0;
	virtual Node * bTRUENode () = 0;
	virtual Node * bFALSENode () = 0;
	virtual Node * bCONTINUENode () = 0;
	virtual Node * bPASSNode () = 0;
	virtual Node * bBREAKNode () = 0; 
	virtual Node * bFLOATNode () = 0;
	virtual Node * bIDENTACIONNode () = 0;
	virtual Node * bIFNode () = 0;
	virtual Node * bFORNode () = 0;
	virtual Node * bRETURNNode () = 0;
	virtual Node * bPRINTNode () = 0;
	virtual Node * bGLOBALNode () = 0;
	virtual Node * bFUNCIONNode () = 0;
	virtual Node * bEXECNode () = 0;
	virtual Node * bWHILENode () = 0;
	virtual Node * bISNode () = 0;
	virtual Node * bANDNode () = 0;
	virtual Node * bORNode () = 0;
	virtual Node * bPORNode () = 0;
	virtual Node * bMENOSNode () = 0;
	virtual Node * bMASNode () = 0;
	virtual Node * bDIVNode () = 0;
	virtual Node * bIGUALNode () = 0;
	virtual Node * bMENORNode () = 0;
	virtual Node * bMAYORNode () = 0;
	virtual Node * bMENIGNode () = 0;
	virtual Node * bMAYIGNode () = 0;
	virtual Node * bMODNode () = 0;
	virtual Node * bDELNode () = 0;
	virtual Node * bNOTNode () = 0;
	virtual Node * bWITHNode () = 0;
	virtual Node * bASNode () = 0;
	virtual Node * bNIGNode () = 0;
	virtual Node * bDIGNode () = 0;
	virtual Node * bENETILDENode () = 0;
	virtual Node * bCIRCUNFLEJONode () = 0;
	virtual Node * bPIPENode () = 0;
	virtual Node * bAMPERSONNode () = 0;
	virtual Node * bDMAYORNode () = 0;
	virtual Node * bbDMENORNode () = 0;
	virtual Node * bDDIAGNode () = 0;
	virtual Node * bDASTERISCOSNode () = 0;
	virtual Node * bAPARENNode () = 0;
	virtual Node * bCPARENNode () = 0;
	virtual Node * bACORCHETENode () = 0;
	virtual Node * bCCORCHETENode () = 0;
	virtual Node * bALLAVENode () = 0;
	virtual Node * bCLLAVENode () = 0;
	virtual Node * bCOMANode () = 0;
	virtual Node * bDPUNTONode () = 0;
	virtual Node * bPUNTONode () = 0;
	virtual Node * bPCOMANode () = 0;
	virtual Node * bMASIGUALNode () = 0;
	virtual Node * bMENOSIGUALNode () = 0;
	virtual Node * bASIGUALNode () = 0;
	virtual Node * bDIAIGUALNode () = 0;
	virtual Node * bDDIAIGUALNode () = 0;
	virtual Node * bPORIGUALNode () = 0;
	virtual Node * bAMPIGUALNode () = 0;
	virtual Node * bPIPEIGUALNode () = 0;
	virtual Node * bCIRCIGUALNode () = 0;
	virtual Node * bDMAYORIGUALNode () = 0;
	virtual Node * bDMENORIGUALNode () = 0;
	virtual Node * bDASTIGUALNode () = 0;
	virtual Node * bMENORMAYORIgual () = 0;
	virtual Node * bNEWLINENode () = 0;
	virtual Node * bDENTACIONNode () = 0;
};
